apiVersion: pxc.percona.com/v1alpha1
kind: PerconaXtraDBCluster
metadata:
  name: cluster1
  finalizers:
    - delete-pxc-pods-in-order
spec:
  secretsName: my-cluster-secrets
  pxc:
    size: 3
    allowUnsafeConfigurations: false
    image: registry.connect.redhat.com/percona/percona-xtradb-cluster-operator-containers:v0.3.0-pxc
    configuration: |
      [mysqld]
      wsrep_debug=ON
    resources:
      requests:
        memory: 1G
        cpu: 600m
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    podDisruptionBudget:
      maxUnavailable: 1
    volumeSpec:
      persistentVolumeClaim:
#        storageClassName: standard
        resources:
          requests:
            storage: 6Gi
  proxysql:
    enabled: true
    size: 1
    image: registry.connect.redhat.com/percona/percona-xtradb-cluster-operator-containers:v0.3.0-proxysql
    resources:
      requests:
        memory: 1G
        cpu: 600m
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    volumeSpec:
      persistentVolumeClaim:
#        storageClassName: standard
        resources:
          requests:
            storage: 2Gi
    podDisruptionBudget:
      maxUnavailable: 1
  pmm:
    enabled: false
  backup:
    image: registry.connect.redhat.com/percona/percona-xtradb-cluster-operator-containers:v0.3.0-backup
    storages:
      s3-us-west:
        type: s3
        s3:
          bucket: S3-BACKUP-BUCKET-NAME-HERE
          credentialsSecret: my-cluster-name-backup-s3
          region: us-west-2
    schedule:
      - name: "sat-night-backup"
        schedule: "0 0 * * 6"
        keep: 3
        storageName: s3-us-west
