apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: cluster1
  finalizers:
    - delete-pxc-pods-in-order
spec:
  secretsName: my-cluster-secrets
  sslSecretName: my-cluster-ssl
  sslInternalSecretName: my-cluster-ssl-internal
  pxc:
    size: 3
    image: registry.connect.redhat.com/percona/percona-xtradb-cluster-operator-containers:1.0.0-pxc
    volumeSpec:
      persistentVolumeClaim:
#        storageClassName: standard
#        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 6Gi
  proxysql:
    enabled: true
    size: 1
    image: registry.connect.redhat.com/percona/percona-xtradb-cluster-operator-containers:1.0.0-proxysql
    volumeSpec:
      persistentVolumeClaim:
#        storageClassName: standard
#        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  pmm:
    enabled: false
  backup:
    image: registry.connect.redhat.com/percona/percona-xtradb-cluster-operator-containers:1.0.0-backup
    storages:
      fs-pvc:
        type: filesystem
        volume:
          persistentVolumeClaim:
#            storageClassName: standard
#            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 6Gi
    schedule:
      - name: "sat-night-backup"
        schedule: "0 0 * * 6"
        keep: 5
        storageName: fs-pvc
